apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-deployment
  namespace: dev
  labels:
    app: user
    env: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      env: dev

  template:
    metadata:
      labels:
        app: user
        env: dev
    spec:
      containers:
        - name: user
          image: user:1
          imagePullPolicy: Never
          ports:
            - name: user-service
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dev
  labels:
    app: user
    env: dev
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: user-service
    nodePort: 30085
  selector:
    app: user
    env: dev
