apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-deployment
  namespace: tst
  labels:
    app: user
    env: tst

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      env: tst

  template:
    metadata:
      labels:
        app: user
        env: tst
    spec:
      containers:
        - name: user
          image: user:1
          imagePullPolicy: Never
          ports:
            - name: user-service
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: tst
  labels:
    app: user
    env: tst
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: user-service
    nodePort: 30088
  selector:
    app: user
    env: tst
