apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  labels:
    app: user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:latest
          ports:
            - name: user-service
            - containerPort: 8080

